### ISSUE TITLE
Issue deploying ELK stack: Data too large, data for [<http_request>]

### ISSUE THREAD

**Issue by AlanPadi95** [AlanPadi95/docker-automation-stack#1]
### Problem description

When I execute `docker stack deploy -c docker-compose.yml elk` Kibana gives me an error and the container stops.

#### Stack configuration

```docker
version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-changeme}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      - discovery.type=single-node
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  logstash:
    image: docker.elastic.co/logstash/logstash:7.5.0
    ports:
      - "5000:5000"
      - "9600:9600"
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      - ELASTIC_USER=${ELASTIC_USER:-elastic}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-changeme}
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    depends_on:
      - elasticsearch  
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    environment:
      - ELASTIC_USER=${ELASTIC_USER:-elastic}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-changeme}
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch  
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
  
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.5.0
    user: root
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD-changeme}
    configs:
      - source: metricbeat_config
        target: /usr/share/metricbeat/metricbeat.yml
    command: -system.hostfs=/hostfs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
      - ./metricbeat/dashboards:/usr/share/metricbeat/kibana/7/dashboard:ro
    depends_on:
      - elasticsearch
      - kibana  
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

configs:
  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
  logstash_config:
    file: ./logstash/config/logstash.yml
  kibana_config:
    file: ./kibana/config/kibana.yml
  metricbeat_config:
    file: ./metricbeat/config/metricbeat.yml

volumes:
  elastic_data:
    driver: local

networks:
  elk:
    driver: overlay
```
#### Docker setup

Docker version 19.03.5, build 633a0ea

docker-compose version 1.24.1, build 4667896b

#### Docker logs

```shell
{"type":"log","@timestamp":"2020-01-15T15:58:30Z","tags":["info","plugins-system"],"pid":6,"message":"Setting up [15] plugins: [security,licensing,code,timelion,features,spaces,translations,uiActions,newsfeed,inspector,embeddable,advancedUiActions,expressions,eui_utils,data]"}
{"type":"log","@timestamp":"2020-01-15T15:58:30Z","tags":["info","plugins","security"],"pid":6,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2020-01-15T15:58:30Z","tags":["warning","plugins","security","config"],"pid":6,"message":"Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in kibana.yml"}
{"type":"log","@timestamp":"2020-01-15T15:58:30Z","tags":["warning","plugins","security","config"],"pid":6,"message":"Session cookies will be transmitted over insecure connections. This is not recommended."}
{"type":"log","@timestamp":"2020-01-15T15:58:30Z","tags":["info","plugins","licensing"],"pid":6,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2020-01-15T15:58:30Z","tags":["info","plugins","code"],"pid":6,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2020-01-15T15:58:30Z","tags":["info","plugins","timelion"],"pid":6,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2020-01-15T15:58:30Z","tags":["info","plugins","features"],"pid":6,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2020-01-15T15:58:30Z","tags":["info","plugins","spaces"],"pid":6,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2020-01-15T15:58:30Z","tags":["info","plugins","translations"],"pid":6,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2020-01-15T15:58:30Z","tags":["info","plugins","data"],"pid":6,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2020-01-15T15:59:12Z","tags":["error","elasticsearch","data"],"pid":6,"message":"Request error, retrying\nGET http://elasticsearch:9200/_xpack => getaddrinfo ENOTFOUND elasticsearch elasticsearch:9200"}
{"type":"log","@timestamp":"2020-01-15T15:59:12Z","tags":["warning","plugins","licensing"],"pid":6,"message":"License information could not be obtained from Elasticsearch for the [data] cluster. Error: Request Timeout after 30000ms"}
{"type":"log","@timestamp":"2020-01-15T15:59:13Z","tags":["warning","legacy-plugins"],"pid":6,"path":"/usr/share/kibana/src/legacy/core_plugins/visualizations","message":"Skipping non-plugin directory at /usr/share/kibana/src/legacy/core_plugins/visualizations"}
{"type":"log","@timestamp":"2020-01-15T15:59:14Z","tags":["warning","elasticsearch","data"],"pid":6,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2020-01-15T15:59:14Z","tags":["warning","elasticsearch","data"],"pid":6,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2020-01-15T15:59:14Z","tags":["warning","elasticsearch","data"],"pid":6,"message":"No living connections"}
{"type":"log","@timestamp":"2020-01-15T15:59:14Z","tags":["warning","plugins","licensing"],"pid":6,"message":"License information could not be obtained from Elasticsearch for the [data] cluster. Error: No Living connections"}
{"type":"log","@timestamp":"2020-01-15T15:59:14Z","tags":["info","plugins-system"],"pid":6,"message":"Starting [8] plugins: [security,licensing,code,timelion,features,spaces,translations,data]"}
{"type":"log","@timestamp":"2020-01-15T15:59:14Z","tags":["error","elasticsearch","admin"],"pid":6,"message":"Request error, retrying\nGET http://elasticsearch:9200/.kibana => connect ECONNREFUSED 10.0.9.8:9200"}
{"type":"log","@timestamp":"2020-01-15T15:59:14Z","tags":["error","elasticsearch","admin"],"pid":6,"message":"Request error, retrying\nGET http://elasticsearch:9200/.kibana_task_manager => connect ECONNREFUSED 10.0.9.8:9200"}
{"type":"log","@timestamp":"2020-01-15T15:59:14Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2020-01-15T15:59:14Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"No living connections"}
{"type":"log","@timestamp":"2020-01-15T15:59:14Z","tags":["warning","migrations"],"pid":6,"message":"Unable to connect to Elasticsearch. Error: No Living connections"}
{"type":"log","@timestamp":"2020-01-15T15:59:14Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2020-01-15T15:59:14Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"No living connections"}
{"type":"log","@timestamp":"2020-01-15T15:59:17Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2020-01-15T15:59:17Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"No living connections"}
{"type":"log","@timestamp":"2020-01-15T15:59:17Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2020-01-15T15:59:17Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"No living connections"}
{"type":"log","@timestamp":"2020-01-15T15:59:19Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2020-01-15T15:59:19Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"No living connections"}
{"type":"log","@timestamp":"2020-01-15T15:59:19Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2020-01-15T15:59:19Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"No living connections"}
{"type":"log","@timestamp":"2020-01-15T15:59:22Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2020-01-15T15:59:22Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"No living connections"}
{"type":"log","@timestamp":"2020-01-15T15:59:22Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"Unable to revive connection: http://elasticsearch:9200/"}
{"type":"log","@timestamp":"2020-01-15T15:59:22Z","tags":["warning","elasticsearch","admin"],"pid":6,"message":"No living connections"}
{"type":"log","@timestamp":"2020-01-15T15:59:26Z","tags":["warning","migrations"],"pid":6,"message":"Unable to connect to Elasticsearch. Error: [search_phase_execution_exception] all shards failed"}
{"type":"log","@timestamp":"2020-01-15T15:59:41Z","tags":["warning","migrations"],"pid":6,"message":"Unable to connect to Elasticsearch. Error: [circuit_breaking_exception] [parent] Data too large, data for [<http_request>] would be [255514104/243.6mb], which is larger than the limit of [246546432/235.1mb], real usage: [255511824/243.6mb], new bytes reserved: [2280/2.2kb], usages [request=0/0b, fielddata=8487/8.2kb, in_flight_requests=2280/2.2kb, accounting=4132841/3.9mb], with { bytes_wanted=255514104 & bytes_limit=246546432 & durability=\"PERMANENT\" }"}
{"type":"log","@timestamp":"2020-01-15T15:59:41Z","tags":["fatal","root"],"pid":6,"message":"{ Error: [circuit_breaking_exception] [parent] Data too large, data for [<http_request>] would be [255514104/243.6mb], which is larger than the limit of [246546432/235.1mb], real usage: [255511824/243.6mb], new bytes reserved: [2280/2.2kb], usages [request=0/0b, fielddata=8487/8.2kb, in_flight_requests=2280/2.2kb, accounting=4132841/3.9mb], with { bytes_wanted=255514104 & bytes_limit=246546432 & durability=\"PERMANENT\" }\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)\n    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4929:19)\n    at IncomingMessage.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1103:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  status: 429,\n  displayName: 'TooManyRequests',\n  message:\n   '[circuit_breaking_exception] [parent] Data too large, data for [<http_request>] would be [255514104/243.6mb], which is larger than the limit of [246546432/235.1mb], real usage: [255511824/243.6mb], new bytes reserved: [2280/2.2kb], usages [request=0/0b, fielddata=8487/8.2kb, in_flight_requests=2280/2.2kb, accounting=4132841/3.9mb], with { bytes_wanted=255514104 & bytes_limit=246546432 & durability=\"PERMANENT\" }',\n  path: '/.kibana_task_manager/_count',\n  query: {},\n  body:\n   { error:\n      { root_cause: [Array],\n        type: 'circuit_breaking_exception',\n        reason:\n         '[parent] Data too large, data for [<http_request>] would be [255514104/243.6mb], which is larger than the limit of [246546432/235.1mb], real usage: [255511824/243.6mb], new bytes reserved: [2280/2.2kb], usages [request=0/0b, fielddata=8487/8.2kb, in_flight_requests=2280/2.2kb, accounting=4132841/3.9mb]',\n        bytes_wanted: 255514104,\n        bytes_limit: 246546432,\n        durability: 'PERMANENT' },\n     status: 429 },\n  statusCode: 429,\n  response:\n   '{\"error\":{\"root_cause\":[{\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be [255514104/243.6mb], which is larger than the limit of [246546432/235.1mb], real usage: [255511824/243.6mb], new bytes reserved: [2280/2.2kb], usages [request=0/0b, fielddata=8487/8.2kb, in_flight_requests=2280/2.2kb, accounting=4132841/3.9mb]\",\"bytes_wanted\":255514104,\"bytes_limit\":246546432,\"durability\":\"PERMANENT\"}],\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be [255514104/243.6mb], which is larger than the limit of [246546432/235.1mb], real usage: [255511824/243.6mb], new bytes reserved: [2280/2.2kb], usages [request=0/0b, fielddata=8487/8.2kb, in_flight_requests=2280/2.2kb, accounting=4132841/3.9mb]\",\"bytes_wanted\":255514104,\"bytes_limit\":246546432,\"durability\":\"PERMANENT\"},\"status\":429}',\n  toString: [Function],\n  toJSON: [Function] }"}
{"type":"log","@timestamp":"2020-01-15T15:59:41Z","tags":["info","plugins-system"],"pid":6,"message":"Stopping all plugins."}
{"type":"log","@timestamp":"2020-01-15T15:59:41Z","tags":["info","plugins","data"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-01-15T15:59:41Z","tags":["info","plugins","translations"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-01-15T15:59:41Z","tags":["info","plugins","spaces"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-01-15T15:59:41Z","tags":["info","plugins","features"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-01-15T15:59:41Z","tags":["info","plugins","timelion"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-01-15T15:59:41Z","tags":["info","plugins","code"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-01-15T15:59:41Z","tags":["info","plugins","licensing"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-01-15T15:59:41Z","tags":["info","plugins","security"],"pid":6,"message":"Stopping plugin"}

 FATAL  [circuit_breaking_exception] [parent] Data too large, data for [<http_request>] would be [255514104/243.6mb], which is larger than the limit of [246546432/235.1mb], real usage: [255511824/243.6mb], new bytes reserved: [2280/2.2kb], usages [request=0/0b, fielddata=8487/8.2kb, in_flight_requests=2280/2.2kb, accounting=4132841/3.9mb], with { bytes_wanted=255514104 & bytes_limit=246546432 & durability="PERMANENT" } :: {"path":"/.kibana_task_manager/_count","query":{},"body":"{\"query\":{\"bool\":{\"should\":[{\"bool\":{\"must\":[{\"exists\":{\"field\":\"graph-workspace\"}},{\"bool\":{\"must_not\":{\"term\":{\"migrationVersion.graph-workspace\":\"7.0.0\"}}}}]}},{\"bool\":{\"must\":[{\"exists\":{\"field\":\"space\"}},{\"bool\":{\"must_not\":{\"term\":{\"migrationVersion.space\":\"6.6.0\"}}}}]}},{\"bool\":{\"must\":[{\"exists\":{\"field\":\"map\"}},{\"bool\":{\"must_not\":{\"term\":{\"migrationVersion.map\":\"7.5.0\"}}}}]}},{\"bool\":{\"must\":[{\"exists\":{\"field\":\"canvas-workpad\"}},{\"bool\":{\"must_not\":{\"term\":{\"migrationVersion.canvas-workpad\":\"7.0.0\"}}}}]}},{\"bool\":{\"must\":[{\"exists\":{\"field\":\"task\"}},{\"bool\":{\"must_not\":{\"term\":{\"migrationVersion.task\":\"7.4.0\"}}}}]}},{\"bool\":{\"must\":[{\"exists\":{\"field\":\"index-pattern\"}},{\"bool\":{\"must_not\":{\"term\":{\"migrationVersion.index-pattern\":\"6.5.0\"}}}}]}},{\"bool\":{\"must\":[{\"exists\":{\"field\":\"visualization\"}},{\"bool\":{\"must_not\":{\"term\":{\"migrationVersion.visualization\":\"7.4.2\"}}}}]}},{\"bool\":{\"must\":[{\"exists\":{\"field\":\"dashboard\"}},{\"bool\":{\"must_not\":{\"term\":{\"migrationVersion.dashboard\":\"7.3.0\"}}}}]}},{\"bool\":{\"must\":[{\"exists\":{\"field\":\"search\"}},{\"bool\":{\"must_not\":{\"term\":{\"migrationVersion.search\":\"7.4.0\"}}}}]}}]}}}","statusCode":429,"response":"{\"error\":{\"root_cause\":[{\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be [255514104/243.6mb], which is larger than the limit of [246546432/235.1mb], real usage: [255511824/243.6mb], new bytes reserved: [2280/2.2kb], usages [request=0/0b, fielddata=8487/8.2kb, in_flight_requests=2280/2.2kb, accounting=4132841/3.9mb]\",\"bytes_wanted\":255514104,\"bytes_limit\":246546432,\"durability\":\"PERMANENT\"}],\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be [255514104/243.6mb], which is larger than the limit of [246546432/235.1mb], real usage: [255511824/243.6mb], new bytes reserved: [2280/2.2kb], usages [request=0/0b, fielddata=8487/8.2kb, in_flight_requests=2280/2.2kb, accounting=4132841/3.9mb]\",\"bytes_wanted\":255514104,\"bytes_limit\":246546432,\"durability\":\"PERMANENT\"},\"status\":429}"}
```

**Comment by AlanPadi95** [comment]
## [SOLVED]

I change the **elasticsearch configuration**. In the `environment` the variable that configure the Java VM. I change the heap memory up to 4GB:

```yml
version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    environment:
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
```
